- hosts: apps
  vars:
    project: tekkool_front
    user: www-data
    group: www-data
    app_path: /var/www/tekkool_front
    home: /var/www

  tasks:
    # APP UPDATE ====================================================
    - name: Pull code from git
      become: true
      become_user: '{{user}}'
      git:
        repo: 'git@gitlab.com:bkinno/tekkool_front.git'
        dest: '{{app_path}}'
        accept_hostkey: yes
        force: yes
        key_file: '{{home}}/.ssh/tekkool_front.priv'
        version: develop

    - name: Install NPM Package
      become: true
      become_user: '{{user}}'
      npm:
        path: '{{app_path}}'

    # RESTART APP ======================================================
    - name: Run Build
      become: true
      become_user: '{{user}}'
      shell: npm run build
      args:
        chdir: '{{app_path}}'