- hosts: apps
  vars:
    project: tekkool_front
    user: www-data
    group: www-data
    app_path: /var/www/tekkool_front
    home: /var/www
  tasks:
    # SYSTEM SETUP ====================================================

    - name: Install system packages
      apt: name="{{item}}" state=present
      with_items:
        - git
        - nginx

    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_8.x xenial main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Remove default config nginx
      file: path=/etc/nginx/sites-enabled/default state=absent

    # UWSGI AND NGINX SETUP ==============================================
    - name: Ensure folders exist with right owner
      file: path={{item}} owner={{user}} group={{group}} state=directory
      with_items:
        - /var/www
        - /var/www/.ssh
        - /var/log/nginx

    - name: Copy config
      template: src="{{item.src}}" dest="{{item.dest}}"
      with_items:
        - { src: 'tekkool_front.nginx.conf', dest: '/etc/nginx/sites-enabled' }

    # APP SETUP ====================================================
    - name: Copy Gitlab SSH Key
      template: src=tekkool_front.priv dest={{home}}/.ssh owner={{user}} group={{group}} mode=0600

    # See: https://stackoverflow.com/a/37096534/100134
    - name: Ensure setfacl support is present.
      package: name=acl

    - name: Clone code from git
      become: true
      become_user: '{{user}}'
      git:
        repo: 'git@gitlab.com:bkinno/tekkool_front.git'
        dest: '{{app_path}}'
        accept_hostkey: yes
        force: yes
        key_file: '{{home}}/.ssh/tekkool_front.priv'
        version: develop

    - name: Install NPM Package
      become: true
      become_user: '{{user}}'
      npm:
        path: '{{app_path}}'

    # RESTART APP ======================================================
    - name: Start services
      service: name={{item}} state=started
      with_items:
        - nginx

    - name: Run Build
      become: true
      become_user: '{{user}}'
      shell: npm run build
      args:
        chdir: '{{app_path}}'